# -*- coding: utf-8 -*-
"""LLJ_OBS

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-altYk9KFPsqNzrQreJBzHTgKiofC3QN
"""

# @title
from datetime import datetime, timezone, timedelta
import os
import requests
import matplotlib
matplotlib.use("Agg")  # headless backend — required for GitHub Actions runners

# ── output directory (GitHub Actions runs headless, so everything gets
#    written to disk instead of using Colab's display()/download buttons) ──
OUTPUT_DIR = os.environ.get("LLJ_OUTPUT_DIR", "output")
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Safe defaults — if a fetch run comes back empty (network blip, no soundings
# available), the later "if n == 0:" branches skip populating these, but the
# coverage map section at the bottom still reads from them.
profile_png_b64 = {}
station_instability = {}
station_cape = {}
wind_png_b64 = {}
station_peak_wind = {}

STATIONS = {
    "Fort Smith":    "gC8J3WBL",
    "Stoney Plain":  "DQ5dW_jH",
    "Fort Nelson":   "n0fezuMf",
    "Prince George": "Yrmut1Ai",
    #"Kelowna":       "jrJ2Lg7d",
    "Norman Wells":  "Y_OSKzQA",
    "Glasgow":       "gJwb_qee",
    "Great Falls":   "h2yCuWZc",
}

def windy_url(station_id, dt):
    ts = int(dt.timestamp() * 1000)
    return (
        f"https://dl.windy.com/obs/measurement/v2/radiosonde/"
        f"{station_id}/download?time={ts}&format=fm94"
    )

now = datetime.now(timezone.utc)
t00 = now.replace(hour=0, minute=0, second=0, microsecond=0)
t12 = now.replace(hour=12, minute=0, second=0, microsecond=0)
if now < t12:
    t12 -= timedelta(days=1)

print(f"Run times:  00Z = {t00.strftime('%Y-%m-%d %HZ')}   12Z = {t12.strftime('%Y-%m-%d %HZ')}")
print(f"Stations: {list(STATIONS.keys())}")

# @title
# ── fetch ───────────────────────────────────────────────────────────────────────
# Run this cell once. Re-run only if you need fresh data from the server.

# ── config ──────────────────────────────────────────────────────────────────────

PLOT_RUN = "12Z"   # must match config cell — change here if you swap runs
ALT_RUN  = "00Z"

import requests

def fetch_sounding_json(url):
    try:
        r = requests.get(url, timeout=30)
        if r.status_code == 200:
            return r.json()
    except Exception as e:
        print(f"  fetch error: {e}")
    return None

raw_geojson = {}   # name -> {run_label -> geojson dict}

#--------------------------------------------------------------------



run_times = {"00Z": t00, "12Z": t12}

for name, sid in STATIONS.items():
    raw_geojson[name] = {}
    for run_label in (PLOT_RUN, ALT_RUN):
        url = windy_url(sid, run_times[run_label])
        gj = fetch_sounding_json(url)
        if gj is None:
            raw_geojson[name][run_label] = None
        else:
            raw_geojson[name][run_label] = gj

# ── report ───────────────────────────────────────────────────────────────────
COL_W = 22
RUN_W = 14

header = f"{'Station':<{COL_W}}" + "".join(f"{r:^{RUN_W}}" for r in (PLOT_RUN, ALT_RUN))
divider = "-" * (COL_W + RUN_W * 2)
print("\n=== Sounding Fetch Report ===\n")
print(header)
print(divider)

total_ok = 0
for name in STATIONS:
    row = f"{name:<{COL_W}}"
    for run_label in (PLOT_RUN, ALT_RUN):
        gj = raw_geojson.get(name, {}).get(run_label)
        if gj is None:
            cell = "✗ FAIL"
        else:
            n_feat = len(gj.get("features", []))
            cell = f"✓ {n_feat} lvls"
            total_ok += 1
        row += f"{cell:^{RUN_W}}"
    print(row)

print(divider)
print(f"\n{total_ok}/{len(STATIONS) * 2} soundings fetched OK.\n")

# drop failed entries so downstream cells stay clean
for name in list(raw_geojson):
    raw_geojson[name] = {k: v for k, v in raw_geojson[name].items() if v is not None}

# @title Upper stations reference
UPPER_AIR_STATIONS = [
    # ── CANADA ──
    {'id':'CYLT', 'name':'Alert',                 'lat':82.50, 'lon':-62.33,  'wmo':'71082'},
    {'id':'CYEU', 'name':'Eureka',                'lat':79.98, 'lon':-85.93,  'wmo':'71917'},
    {'id':'YUX', 'name':'HALL BEACH ',             'lat':68.77, 'lon':-81.23,  'wmo':'71081'},
    {'id':'YRB',  'name':'Resolute Bay',           'lat':74.72, 'lon':-94.98,  'wmo':'71924'},
    {'id':'YCB',  'name':'Clyde River',            'lat':70.49, 'lon':-68.52,  'wmo':'71925'},
    {'id':'CYFB', 'name':'Iqaluit',                'lat':63.75, 'lon':-68.53,  'wmo':'71909'},
    {'id':'YBK',  'name':'Baker Lake',             'lat':64.30, 'lon':-96.00,  'wmo':'71926'},
    {'id':'CYRK', 'name':'Rankin Inlet',           'lat':62.82, 'lon':-92.12,  'wmo':'71907'},
    {'id':'CYVP', 'name':'Kuujjuaq',               'lat':58.10, 'lon':-68.42,  'wmo':'71906'},
 #   {'id':'CYCO', 'name':'Coral Harbour',          'lat':64.19, 'lon':-83.36,  'wmo':'71815'},
    {'id':'YYR',  'name':'Goose Bay',              'lat':53.31, 'lon':-60.36,  'wmo':'71816'},
 #   {'id':'CYYT', 'name':"St. John's",             'lat':47.62, 'lon':-52.74,  'wmo':'71801'},
 #   {'id':'CYSJ', 'name':'Sable Island',           'lat':43.93, 'lon':-60.02,  'wmo':'71600'},
    {'id':'CYHZ', 'name':'Yarmouth',               'lat':43.83, 'lon':-66.08,  'wmo':'71603'},
    {'id':'CYBG', 'name':'Bagotville',             'lat':48.33, 'lon':-70.99,  'wmo':'71722'},
#    {'id':'CYYY', 'name':'Mont Joli',              'lat':48.60, 'lon':-68.22,  'wmo':'71714'},
#    {'id':'CYBR', 'name':'Brandon',                'lat':49.91, 'lon':-99.95,  'wmo':'71869'},
    {'id':'CYMX', 'name':'Maniwaki',               'lat':46.37, 'lon':-75.98,  'wmo':'71722'},
 #   {'id':'CYLA', 'name':'La Grande IV',           'lat':53.75, 'lon':-73.67,  'wmo':'71823'},
 #   {'id':'CYMO', 'name':'Moosonee',               'lat':51.29, 'lon':-80.60,  'wmo':'71836'},
    {'id':'CYTL', 'name':'Big Trout Lake',         'lat':53.82, 'lon':-89.87,  'wmo':'71845'},
 #   {'id':'CYYU', 'name':'Kapuskasing',            'lat':49.41, 'lon':-82.47,  'wmo':'71731'},
    {'id':'YYQ',  'name':'Churchill',              'lat':58.75, 'lon':-94.07,  'wmo':'71913'},
    {'id':'YQD',  'name':'The Pas',                'lat':53.97, 'lon':-101.10, 'wmo':'71867'},
#    {'id':'CYXE', 'name':'Saskatoon',              'lat':52.17, 'lon':-106.68, 'wmo':'71866'},
    {'id':'WSE', 'name':'Stoney Plain',   'lat':53.55, 'lon':-114.11, 'wmo':'71119'},
    {'id':'YSM',  'name':'Fort Smith',             'lat':60.02, 'lon':-111.96, 'wmo':'71934'},
    {'id':'YVQ',  'name':'Norman Wells',           'lat':65.28, 'lon':-126.80, 'wmo':'71043'},
    {'id':'YXY',  'name':'Whitehorse',             'lat':60.72, 'lon':-135.07, 'wmo':'71964'},
    {'id':'YYE',  'name':'Fort Nelson',            'lat':58.84, 'lon':-122.60, 'wmo':'71945'},
    {'id':'YEV',  'name':'Inuvik',                 'lat':68.30, 'lon':-133.48, 'wmo':'71957'},
    {'id':'ZXS', 'name':'Prince George',          'lat':53.88, 'lon':-122.68, 'wmo':'71908'},
    {'id':'WLW', 'name':'Vernon',                 'lat':50.24, 'lon':-119.29, 'wmo':'73033'},
    {'id':'YZT',  'name':'Port Hardy',             'lat':50.68, 'lon':-127.37, 'wmo':'71109'},
    # ── ALASKA ──
    #{'id':'BRW',  'name':'Utqiagvik (Barrow)',     'lat':71.30, 'lon':-156.78, 'wmo':'70026'},
  #  {'id':'OTZ',  'name':'Kotzebue',               'lat':66.87, 'lon':-162.63, 'wmo':'70133'},
    {'id':'OME',  'name':'Nome',                   'lat':64.50, 'lon':-165.43, 'wmo':'70200'},
    {'id':'BET',  'name':'Bethel',                 'lat':60.78, 'lon':-161.80, 'wmo':'70219'},
    {'id':'MCG',  'name':'McGrath',                'lat':62.97, 'lon':-155.62, 'wmo':'70231'},
    {'id':'FAI',  'name':'Fairbanks',              'lat':64.82, 'lon':-147.87, 'wmo':'70261'},
    {'id':'ANC',  'name':'Anchorage',              'lat':61.17, 'lon':-150.02, 'wmo':'70273'},
    {'id':'AKN',  'name':'King Salmon',            'lat':58.68, 'lon':-156.65, 'wmo':'70326'},
    {'id':'PACD', 'name':'Cold Bay',               'lat':55.20, 'lon':-162.73, 'wmo':'70316'},
    {'id':'PADQ', 'name':'Kodiak',                 'lat':57.75, 'lon':-152.50, 'wmo':'70350'},
   # {'id':'NHB',  'name':'St Paul Island',         'lat':57.15, 'lon':-170.22, 'wmo':'70308'},
    {'id':'ANN',  'name':'Annette Island',         'lat':55.03, 'lon':-131.57, 'wmo':'70398'},
    {'id':'YAK',  'name':'Yakutat',                'lat':59.52, 'lon':-139.67, 'wmo':'70361'},
    # ── CONTIGUOUS US ──
    {'id':'SLE',  'name':'Salem',                  'lat':44.91, 'lon':-123.01, 'wmo':'72694'},
    {'id':'UIL',  'name':'Quillayute WA',          'lat':47.95, 'lon':-124.55, 'wmo':'72797'},
    {'id':'SLC',  'name':'Salt Lake City UT',      'lat':40.77, 'lon':-111.97, 'wmo':'72572'},
    {'id':'BOI',  'name':'Boise ID',               'lat':43.57, 'lon':-116.22, 'wmo':'72681'},
    {'id':'EKO',  'name':'Elko NV',                'lat':40.87, 'lon':-115.73, 'wmo':'72582'},
    {'id':'KOAK', 'name':'Oakland CA',             'lat':37.73, 'lon':-122.22, 'wmo':'72493'},
  #  {'id':'KVBG', 'name':'Vandenberg CA',          'lat':34.73, 'lon':-120.57, 'wmo':'72393'},
    {'id':'MFR',  'name':'Medford OR',             'lat':42.37, 'lon':-122.87, 'wmo':'72597'},
    {'id':'GGW',  'name':'Glasgow MT',             'lat':48.21, 'lon':-106.62, 'wmo':'72768'},
    {'id':'RIW',  'name':'Riverton WY',            'lat':43.07, 'lon':-108.48, 'wmo':'72672'},
    {'id':'KGJT', 'name':'Grand Junction CO',      'lat':39.12, 'lon':-108.53, 'wmo':'72476'},
    {'id':'KFGZ', 'name':'Flagstaff AZ',           'lat':35.23, 'lon':-111.82, 'wmo':'72376'},
    {'id':'KVEF', 'name':'Las Vegas NV',           'lat':36.08, 'lon':-115.17, 'wmo':'72388'},
    {'id':'KABQ', 'name':'Albuquerque NM',         'lat':35.05, 'lon':-106.62, 'wmo':'72365'},
    {'id':'BIS',  'name':'Bismarck ND',            'lat':46.77, 'lon':-100.75, 'wmo':'72764'},
    {'id':'ABR',  'name':'Aberdeen SD',            'lat':45.45, 'lon':-98.42,  'wmo':'72659'},
    {'id':'RAP',  'name':'Rapid City SD',          'lat':44.07, 'lon':-103.22, 'wmo':'72662'},
    {'id':'KDDC', 'name':'Dodge City KS',          'lat':37.77, 'lon':-99.97,  'wmo':'72451'},
    {'id':'KTOP', 'name':'Topeka KS',              'lat':39.07, 'lon':-95.63,  'wmo':'72456'},
    {'id':'KAMA', 'name':'Amarillo TX',            'lat':35.22, 'lon':-101.72, 'wmo':'72363'},
    {'id':'OUN',  'name':'Norman OK',              'lat':35.18, 'lon':-97.43,  'wmo':'72357'},
 #   {'id':'KEPZ', 'name':'Santa Teresa NM',        'lat':31.87, 'lon':-106.70, 'wmo':'72270'},
    {'id':'KMAF', 'name':'Midland TX',             'lat':31.95, 'lon':-102.18, 'wmo':'72265'},
    {'id':'FWD', 'name':'Fort Worth TX',             'lat':32.84, 'lon':-97.30, 'wmo':'72249'},
    {'id':'KDRT', 'name':'Del Rio TX',             'lat':29.37, 'lon':-100.92, 'wmo':'72261'},
    {'id':'KCRP', 'name':'Corpus Christi TX',      'lat':27.77, 'lon':-97.50,  'wmo':'72251'},
    {'id':'INL',  'name':'International Falls MN', 'lat':48.57, 'lon':-93.38,  'wmo':'72747'},
    {'id':'MPX',  'name':'Minneapolis MN',         'lat':44.85, 'lon':-93.57,  'wmo':'72649'},
    {'id':'LBF',  'name':'North Platte NE',        'lat':41.13, 'lon':-100.68, 'wmo':'72562'},
  ##  {'id':'OAX',  'name':'Omaha NE',               'lat':41.32, 'lon':-96.37,  'wmo':'72553'},
    {'id':'KILX', 'name':'Lincoln IL',             'lat':40.15, 'lon':-89.33,  'wmo':'72440'},
    {'id':'KDVN', 'name':'Davenport IA',           'lat':41.62, 'lon':-90.58,  'wmo':'74455'},
    {'id':'KSGF', 'name':'Springfield MO',         'lat':37.23, 'lon':-93.38,  'wmo':'72440'},
    {'id':'KBUF', 'name':'Buffalo NY',             'lat':42.93, 'lon':-78.73,  'wmo':'72528'},
    {'id':'KGYX', 'name':'Gray ME',                'lat':43.90, 'lon':-70.25,  'wmo':'74389'},
    {'id':'KSHV', 'name':'Shreveport LA',          'lat':32.45, 'lon':-93.82,  'wmo':'72248'},
    {'id':'KLCH', 'name':'Lake Charles LA',        'lat':30.12, 'lon':-93.22,  'wmo':'72240'},
    {'id':'KLIX', 'name':'New Orleans LA',         'lat':30.33, 'lon':-89.82,  'wmo':'72233'},
    {'id':'PHTO', 'name':'Hilo',                   'lat':19.72, 'lon':-155.05, 'wmo':'91285'},
    {'id':'PHLI', 'name':'Lihue',                  'lat':21.99, 'lon':-159.34, 'wmo':'91165'},

]

# @title
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import json

# ── helpers ────────────────────────────────────────────────────────────────────

def fetch_sounding_json(url):
    try:
        r = requests.get(url, timeout=30)
        if r.status_code == 200:
            return r.json()
    except Exception as e:
        print(f"  fetch error: {e}")
    return None

def parse_sounding(geojson):
    """Extract pressure (hPa), height (m MSL), and wind speed (kt) from FM94 GeoJSON."""
    pres, wspd, height = [], [], []
    for feat in geojson.get("features", []):
        if feat["geometry"]["type"] != "Point":
            continue
        p  = feat["properties"]
        pr = p.get("pressure")
        u  = p.get("wind_u")
        v  = p.get("wind_v")
        h  = p.get("gpheight")
        if pr is None or u is None or v is None or h is None:
            continue
        spd_ms = np.sqrt(u**2 + v**2)
        spd_kt = spd_ms * 1.94384
        pres.append(pr)
        wspd.append(spd_kt)
        height.append(h)
    return np.array(pres), np.array(wspd), np.array(height)

def find_wmo(sta_name):
    """Match station name against UPPER_AIR_STATIONS, return wmo id or None."""
    norm = sta_name.lower().replace(",", "").strip()
    # strip trailing network/region tokens like "ua" or "us"
    tokens = norm.split()
    if tokens and tokens[-1] in ("ua", "us"):
        tokens = tokens[:-1]
    norm = " ".join(tokens)
    for sta in UPPER_AIR_STATIONS:
        sta_norm = sta["name"].lower().replace(",", "").strip()
        if sta_norm == norm or sta_norm in norm or norm in sta_norm:
            return sta["wmo"]
    return None

def sounding_meta(geojson):
    p = geojson.get("properties", {})
    name = p.get("station_name", "Unknown")
    ts   = p.get("syn_timestamp") or p.get("firstSeen")
    if ts:
        dt = datetime.fromtimestamp(ts, tz=timezone.utc)
        time_str = dt.strftime("%Y-%m-%d %HZ")
        if dt.hour == 12:
            time_str += " [6AM MDT]"
        elif dt.hour == 0:
            time_str += " [6PM MDT]"
    else:
        time_str = "Unknown time"
    return name, time_str

# ── config ──────────────────────────────────────────────────────────────────────

PLOT_RUN   = "12Z"          # "12Z" or "00Z" — swap here to change focus
ALT_RUN    = "00Z"
PRES_FLOOR = 100            # hPa — don't plot above this
PRES_CEIL  = 1050           # hPa — not used for y-axis anymore but kept for mask
HEIGHT_FLOOR_M = 0
HEIGHT_CEIL_M  = 15000      # m



# ── plot ────────────────────────────────────────────────────────────────────────

# ── build soundings dict from raw_geojson (if not already built) ────────────
soundings = {}
for name, runs in raw_geojson.items():
    for run_label, gj in runs.items():
        pres, wspd, height = parse_sounding(gj)
        if len(pres) == 0:
            continue
        sta_name, time_str = sounding_meta(gj)
        wmo_id = find_wmo(sta_name)
        clean_name = sta_name
        clean_tokens = clean_name.split()
        if clean_tokens and clean_tokens[-1].lower() in ("ua", "us"):
            clean_name = " ".join(clean_tokens[:-1])
        clean_name = clean_name.rstrip(",").strip()
        title_name = f"{wmo_id} {clean_name}" if wmo_id else clean_name
        key = f"{name} {run_label}"
        soundings[key] = {
            "pres":   pres,
            "wspd":   wspd,
            "height": height,
            "title":  f"{title_name}\n{time_str}",
            "run":    run_label,
        }
print(f"Built {len(soundings)} soundings from raw_geojson.")

n = len(soundings)






if n == 0:
    print("No soundings available to plot.")
else:
    COLS  = 4
    ROWS  = (n + COLS - 1) // COLS
    FW    = 5 * COLS
    FH    = 5 * ROWS + 1.2   # extra for suptitle

    fig, axes = plt.subplots(ROWS, COLS, figsize=(FW, FH),
                             sharey=False, squeeze=False)

    HEIGHT_TICKS_M = list(range(0, 16000, 1000))  # 0–15 km, every 1 km
    MAX_WSPD       = 120    # kt

    # pressure levels to mark as horizontal dashed lines
    # stored as (pressure_hPa, color, label)
    PRES_MARKERS = [
        (925, "#2ca02c", "925 hPa"),   # green
        (850, "#9467bd", "850 hPa"),   # purple
    ]

    for ax_idx, (key, sd) in enumerate(soundings.items()):
        row, col = divmod(ax_idx, COLS)
        ax = axes[row][col]

        mask = (sd["height"] >= HEIGHT_FLOOR_M) & (sd["height"] <= HEIGHT_CEIL_M)
        for ws_line in range(0, MAX_WSPD + 1, 10):
            ax.axvline(ws_line, color="#bbbbbb", lw=0.6, ls="--", zorder=1)
        ax.plot(sd["wspd"][mask], sd["height"][mask] / 1000,
                color="#d62728", lw=1.8, zorder=3)

        # draw pressure-level markers converted to height via interpolation
        for p_mark, p_color, p_label in PRES_MARKERS:
            # interpolate height at this pressure level from sounding data
            # sort by pressure descending (surface first) for interp
            sort_idx = np.argsort(sd["pres"])[::-1]
            pres_s   = sd["pres"][sort_idx]
            hgt_s    = sd["height"][sort_idx]
            if pres_s.min() <= p_mark <= pres_s.max():
                h_mark = float(np.interp(p_mark, pres_s[::-1], hgt_s[::-1])) / 1000
                ax.axhline(h_mark, color=p_color, lw=1.2, ls="--",
                           zorder=2, alpha=0.85)
                ax.text(MAX_WSPD * 0.98, h_mark, p_label,
                        color=p_color, fontsize=6, va="bottom", ha="right")
            else:
                fallback_h = 0.8 if p_mark == 925 else 1.4
                ax.axhline(fallback_h, color=p_color, lw=1.2, ls="--",
                           zorder=2, alpha=0.85)
                ax.text(MAX_WSPD * 0.98, fallback_h, p_label,
                        color=p_color, fontsize=5, va="bottom", ha="right")

        ax.set_ylim(HEIGHT_FLOOR_M / 1000, HEIGHT_CEIL_M / 1000)
        ax.set_yticks([h / 1000 for h in HEIGHT_TICKS_M])
        ax.set_yticklabels([f"{h/1000:.0f}" for h in HEIGHT_TICKS_M], fontsize=7)
        ax.set_xlim(0, MAX_WSPD)
        ax.set_xlabel("Wind speed (kt)", fontsize=8)
        ax.set_ylabel("Height (km)", fontsize=8)
        ax.grid(True, ls="--", lw=0.4, alpha=0.5)
        ax.tick_params(axis="x", labelsize=7)

        ax.set_title(sd["title"].replace("\n", " — "),
                     fontsize=8, fontweight="bold", pad=4)

    # hide unused subplots
    for i in range(n, ROWS * COLS):
        axes[i // COLS][i % COLS].set_visible(False)

    run_date = (t12 if PLOT_RUN == "12Z" else t00).strftime("%Y-%m-%d")
    fig.suptitle(
        f"Upper-air Wind Speed Profiles — {PLOT_RUN} ({run_date})",
        fontsize=13, fontweight="bold", y=1.01
    )

    plt.tight_layout()
    run_date = (t12 if PLOT_RUN == "12Z" else t00).strftime("%Y-%m-%d")

    # ── save individual PNGs and bundle into zip ────────────────────────────
    import io, zipfile
    import base64

    zip_buf = io.BytesIO()
    saved_files = []
    wind_png_b64 = {}      # {(name, run): base64 PNG string} — used by the coverage map cell
    station_peak_wind = {} # {(name, run): peak wind kt <800mb} — used by the coverage map cell

    with zipfile.ZipFile(zip_buf, "w", zipfile.ZIP_DEFLATED) as zf:
        # combined overview PNG
        overview_name = f"windspeed_profiles_{PLOT_RUN}_{run_date}.png"
        buf = io.BytesIO()
        fig.savefig(buf, dpi=150, bbox_inches="tight", format="png")
        buf.seek(0)
        overview_png_bytes = buf.read()
        zf.writestr(overview_name, overview_png_bytes)
        saved_files.append(overview_name)
        wind_overview_b64 = base64.b64encode(overview_png_bytes).decode()

        # individual station PNGs
        for ax_idx, (key, sd) in enumerate(soundings.items()):
            row, col = divmod(ax_idx, COLS)
            ax = axes[row][col]

            fig_single, ax_s = plt.subplots(figsize=(4, 6))
            mask = (sd["height"] >= HEIGHT_FLOOR_M) & (sd["height"] <= HEIGHT_CEIL_M)
            for ws_line in range(0, MAX_WSPD + 1, 10):
                ax_s.axvline(ws_line, color="#bbbbbb", lw=0.6, ls="--", zorder=1)
            ax_s.plot(sd["wspd"][mask], sd["height"][mask] / 1000,
                      color="#d62728", lw=1.8, zorder=3)

            for p_mark, p_color, p_label in PRES_MARKERS:
                sort_idx = np.argsort(sd["pres"])[::-1]
                pres_s   = sd["pres"][sort_idx]
                hgt_s    = sd["height"][sort_idx]
                if pres_s.min() <= p_mark <= pres_s.max():
                    h_mark = float(np.interp(p_mark, pres_s[::-1], hgt_s[::-1])) / 1000
                    ax_s.axhline(h_mark, color=p_color, lw=1.2, ls="--",
                                 zorder=2, alpha=0.85)
                    ax_s.text(MAX_WSPD * 0.98, h_mark, p_label,
                              color=p_color, fontsize=7, va="bottom", ha="right")
                else:
                    fallback_h = 0.8 if p_mark == 925 else 1.4
                    ax_s.axhline(fallback_h, color=p_color, lw=1.2, ls="--",
                                 zorder=2, alpha=0.85)
                    ax_s.text(MAX_WSPD * 0.98, fallback_h, p_label,
                              color=p_color, fontsize=7, va="bottom", ha="right")

            ax_s.set_ylim(HEIGHT_FLOOR_M / 1000, HEIGHT_CEIL_M / 1000)
            ax_s.set_yticks([h / 1000 for h in HEIGHT_TICKS_M])
            ax_s.set_yticklabels([f"{h/1000:.0f}" for h in HEIGHT_TICKS_M], fontsize=8)
            ax_s.set_xlim(0, MAX_WSPD)
            ax_s.set_xlabel("Wind speed (kt)", fontsize=9)
            ax_s.set_ylabel("Height (km)", fontsize=9)
            ax_s.grid(True, ls="--", lw=0.4, alpha=0.5)
            ax_s.set_title(sd["title"].replace("\n", " — "),
                           fontsize=9, fontweight="bold")
            fig_single.tight_layout()

            run_dt   = t12 if sd["run"] == "12Z" else t00
            run_tag  = run_dt.strftime("%H%Z%d%b%Y").upper().replace("UTC", "Z")
            station_name = " ".join(key.split(" ")[:-1])
            safe_name = station_name.replace(" ", "_").replace("/", "-")
            fname = f"{safe_name}_{run_tag}_WINDS.png"
            buf_s = io.BytesIO()
            fig_single.savefig(buf_s, dpi=150, bbox_inches="tight", format="png")
            buf_s.seek(0)
            png_bytes = buf_s.read()
            zf.writestr(fname, png_bytes)
            saved_files.append(fname)
            wind_png_b64[(station_name, sd["run"])] = base64.b64encode(png_bytes).decode()

            sub800_mask = sd["pres"] >= 800
            if sub800_mask.any():
                peak_wind = float(np.max(sd["wspd"][sub800_mask]))
            else:
                peak_wind = None
            station_peak_wind[(station_name, sd["run"])] = peak_wind

            plt.close(fig_single)

    zip_buf.seek(0)

    import base64
    wind_zip_b64 = base64.b64encode(zip_buf.read()).decode()
    wind_zip_filename = f"winds_{PLOT_RUN}_{run_date}.zip"
    wind_zip_path = os.path.join(OUTPUT_DIR, wind_zip_filename)

    plt.close(fig)
    print(f"\nZip ready: {wind_zip_filename}  ({len(saved_files)} PNGs)")

    with open(wind_zip_path, "wb") as f:
        zip_buf.seek(0)
        f.write(zip_buf.read())

    print(f"Saved: {wind_zip_path}")

# @title  Tephigram + CAPE
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
from datetime import datetime, timezone

# ── thermodynamic constants ───────────────────────────────────────────────────
Rd   = 287.05    # J kg-1 K-1
Rv   = 461.5
Cp   = 1005.7
Lv   = 2.501e6
eps  = Rd / Rv   # 0.622
kd   = Rd / Cp   # 0.2854  (dry adiabatic lapse rate exponent)

P0   = 1000.0    # hPa reference pressure

# ── helper functions ──────────────────────────────────────────────────────────

def theta(T_K, p_hPa):
    """Potential temperature (K)."""
    return T_K * (P0 / p_hPa) ** kd

def es(T_K):
    """Saturation vapour pressure (hPa) — Bolton 1980."""
    T_C = T_K - 273.15
    return 6.112 * np.exp(17.67 * T_C / (T_C + 243.5))

def mixr_sat(T_K, p_hPa):
    """Saturation mixing ratio (kg/kg)."""
    e_s = es(T_K)
    return eps * e_s / (p_hPa - e_s)

def theta_e(T_K, Td_K, p_hPa):
    """Equivalent potential temperature (K) — Bolton 1980 eq 43."""
    r  = mixr_sat(Td_K, p_hPa)           # mixing ratio at dewpoint ≈ actual r
    TL = 56 + 1.0 / (1.0 / (Td_K - 56) + np.log(T_K / Td_K) / 800.0)
    return T_K * (P0 / p_hPa) ** (0.2854 * (1 - 0.28e-3 * r * 1000)) \
           * np.exp((3.376 / TL - 0.00254) * r * 1000 * (1 + 0.81e-3 * r * 1000))

def lcl(T_K, Td_K, p_hPa):
    """LCL temperature and pressure (K, hPa) — Bolton 1980."""
    TL = 56 + 1.0 / (1.0 / (Td_K - 56) + np.log(T_K / Td_K) / 800.0)
    pL = p_hPa * (TL / T_K) ** (1.0 / kd)
    return TL, pL

def moist_adiabat(T_K, p_hPa, p_top=100.0, dp=-2.0):
    """
    Follow a saturated adiabat from (T_K, p_hPa) upward.
    Returns arrays of (p, T) along the parcel path.
    """
    p_arr, T_arr = [p_hPa], [T_K]
    p = p_hPa
    T = T_K
    while p > p_top:
        p_new = p + dp
        # pseudo-adiabatic lapse rate
        r_s  = mixr_sat(T, p)
        numer = (Rd * T + Lv * r_s)
        denom = p * (Cp + Lv**2 * r_s * eps / (Rd * T**2))
        dT_dp = numer / denom          # K/hPa
        T = T + dT_dp * dp
        p = p_new
        p_arr.append(p)
        T_arr.append(T)
    return np.array(p_arr), np.array(T_arr)

def compute_cape_cin(p_arr, T_arr, Td_arr):
    """
    Surface-based CAPE and CIN (J/kg).
    Lifts surface parcel dry to LCL, then moist adiabatically to top.
    """
    # sort surface→top
    idx  = np.argsort(p_arr)[::-1]
    p    = p_arr[idx]
    T    = T_arr[idx]
    Td   = Td_arr[idx]

    # surface parcel
    T0, Td0, p0 = T[0], Td[0], p[0]
    th0  = theta(T0, p0)
    TL, pL = lcl(T0, Td0, p0)

    # parcel temperature along dry adiabat (surface → LCL)
    def parcel_dry(p_lev):
        return th0 * (p_lev / P0) ** kd

    # parcel path above LCL along moist adiabat
    p_moist, T_moist = moist_adiabat(TL, pL, p_top=max(p[-1], 100.0))

    def parcel_T(p_lev):
        if p_lev >= pL:
            return parcel_dry(p_lev)
        else:
            return float(np.interp(p_lev, p_moist[::-1], T_moist[::-1]))

    CAPE = 0.0
    CIN  = 0.0
    for i in range(len(p) - 1):
        p_mid = 0.5 * (p[i] + p[i+1])
        T_env = 0.5 * (T[i] + T[i+1])
        T_par = parcel_T(p_mid)
        # dz via hypsometric
        dz = -Rd * T_env / (9.81 * p_mid) * (p[i+1] - p[i]) * 100.0
        buoy = 9.81 * (T_par - T_env) / T_env * dz
        if buoy > 0:
            CAPE += buoy
        else:
            if CAPE == 0.0:   # still below LFC
                CIN += buoy

    return CAPE, CIN, pL, TL

def find_mu_index(p_arr, T_arr):
    """Index of the warmest level at or below 850 hPa (most-unstable source level)."""
    mask = p_arr >= 850
    if not mask.any():
        mask = np.ones_like(p_arr, dtype=bool)
    idxs = np.where(mask)[0]
    return idxs[np.argmax(T_arr[idxs])]

def compute_cape_from_level(p_arr, T_arr, Td_arr, idx0, Td_surface=None):
    """CAPE/CIN lifting a parcel from an arbitrary level (arrays already surface→top sorted).

    Td_surface: if provided, use this as the parcel's source dewpoint instead of
    Td_arr[idx0]. This matches the convention that the MU parcel is lifted from
    the warmest sub-850hPa level but should carry the actual surface moisture,
    not the dewpoint observed at that elevated level.
    """
    p, T, Td = p_arr[idx0:], T_arr[idx0:], Td_arr[idx0:]
    T0, p0 = T[0], p[0]
    Td0 = Td_surface if Td_surface is not None else Td[0]
    th0 = theta(T0, p0)
    TL, pL = lcl(T0, Td0, p0)

    def parcel_dry(p_lev):
        return th0 * (p_lev / P0) ** kd

    p_moist, T_moist = moist_adiabat(TL, pL, p_top=p[-1])

    def parcel_T(p_lev):
        if p_lev >= pL:
            return parcel_dry(p_lev)
        else:
            return float(np.interp(p_lev, p_moist[::-1], T_moist[::-1]))

    CAPE = 0.0
    CIN  = 0.0
    above_LFC = False
    for i in range(len(p) - 1):
        p_mid = 0.5 * (p[i] + p[i+1])
        T_env = 0.5 * (T[i] + T[i+1])
        T_par = parcel_T(p_mid)
        dz = -Rd * T_env / (9.81 * p_mid) * (p[i+1] - p[i]) * 100.0
        buoy = 9.81 * (T_par - T_env) / T_env * dz
        if buoy > 0:
            CAPE += buoy
            above_LFC = True
        elif not above_LFC:
            CIN += buoy

    return CAPE, CIN, pL, TL

# ── tephigram coordinate transforms ──────────────────────────────────────────
# x = temperature on skew-T (°C + skew offset)
# y = log-pressure for plot y-axis
# We use a standard skew-T log-P layout (simpler than true tephigram,
# but meteorologically equivalent and far more readable)

SKEW  = 45.0   # degrees of skew (standard)

def skewx(T_C, p_hPa):
    """X position: temperature skewed by log(p)."""
    return T_C - SKEW * np.log(p_hPa / P0)

# ── parse all soundings ────────────────────────────────────────────────────────

def find_wmo(sta_name):
    """Match station name against UPPER_AIR_STATIONS, return wmo id or None."""
    norm = sta_name.lower().replace(",", "").strip()
    tokens = norm.split()
    if tokens and tokens[-1] in ("ua", "us"):
        tokens = tokens[:-1]
    norm = " ".join(tokens)
    for sta in UPPER_AIR_STATIONS:
        sta_norm = sta["name"].lower().replace(",", "").strip()
        if sta_norm == norm or sta_norm in norm or norm in sta_norm:
            return sta["wmo"]
    return None

def sounding_meta(geojson):
    p = geojson.get("properties", {})
    name = p.get("station_name", "Unknown")
    ts   = p.get("syn_timestamp") or p.get("firstSeen")
    if ts:
        dt = datetime.fromtimestamp(ts, tz=timezone.utc)
        time_str = dt.strftime("%Y-%m-%d %HZ")
        if dt.hour == 12:
            time_str += " [6AM MDT]"
        elif dt.hour == 0:
            time_str += " [6PM MDT]"
    else:
        time_str = "Unknown time"
    return name, time_str

def build_title(geojson, fallback_name, run):
    """Build a 'WMO_ID Station Name — Date HHZ [local time]' title, matching the wind-speed script."""
    try:
        sta_name, time_str = sounding_meta(geojson)
        wmo_id = find_wmo(sta_name)
        clean_name = sta_name
        clean_tokens = clean_name.split()
        if clean_tokens and clean_tokens[-1].lower() in ("ua", "us"):
            clean_name = " ".join(clean_tokens[:-1])
        clean_name = clean_name.rstrip(",").strip()
        title_name = f"{wmo_id} {clean_name}" if wmo_id else clean_name
        return f"{title_name} — {time_str}"
    except Exception:
        return f"{fallback_name}  [{run}]"

def parse_full(geojson):
    p, T, Td, u, v, h = [], [], [], [], [], []
    for feat in geojson.get("features", []):
        if feat["geometry"]["type"] != "Point":
            continue
        pr = feat["properties"]
        if any(pr.get(k) is None for k in ("pressure","temp","dewpoint","wind_u","wind_v","gpheight")):
            continue
        p.append(pr["pressure"])
        T.append(pr["temp"])        # K
        Td.append(pr["dewpoint"])   # K
        u.append(pr["wind_u"])
        v.append(pr["wind_v"])
        h.append(pr["gpheight"])
    arr = np.array
    return arr(p), arr(T), arr(Td), arr(u), arr(v), arr(h)

# ── plot layout ───────────────────────────────────────────────────────────────

PLOT_RUN = PLOT_RUN   # from config cell
PRES_LEVELS = [1000, 925, 850, 700, 500, 400, 300, 200, 150, 100]
T_MIN, T_MAX = -50, 40    # °C display range at P0
P_TOP, P_BOT = 100, 1050  # hPa

COLS = 4
# show every available run (00Z and/or 12Z) for every station, matching the wind-speed script
station_keys = []
for name in STATIONS:
    for run_label in ("12Z", "00Z"):
        if raw_geojson.get(name, {}).get(run_label):
            station_keys.append((name, run_label))

n = len(station_keys)
if n == 0:
    print("No sounding data available.")
else:
    ROWS = (n + COLS - 1) // COLS
    fig, axes = plt.subplots(ROWS, COLS, figsize=(6*COLS, 8*ROWS), squeeze=False)

    cape_summary = []

    for idx, (name, run) in enumerate(station_keys):
        ax = axes[idx // COLS][idx % COLS]
        gj = raw_geojson[name][run]
        p, T_K, Td_K, u, v, h = parse_full(gj)

        if len(p) < 5:
            ax.set_visible(False)
            continue

        # sort surface→top
        si   = np.argsort(p)[::-1]
        p    = p[si];  T_K = T_K[si];  Td_K = Td_K[si]
        u    = u[si];  v   = v[si]
        T_C  = T_K - 273.15
        Td_C = Td_K - 273.15

        # ── CAPE / CIN ────────────────────────────────────────────────────
        try:
            CAPE, CIN, pLCL, TLCL = compute_cape_cin(p, T_K, Td_K)
        except Exception:
            CAPE, CIN, pLCL, TLCL = 0, 0, p[0], T_K[0]

        try:
            mu_idx = find_mu_index(p, T_K)
            MUCAPE, MUCIN, pLCL_mu, TLCL_mu = compute_cape_from_level(p, T_K, Td_K, mu_idx, Td_surface=Td_K[0])
        except Exception:
            mu_idx = 0
            MUCAPE, MUCIN, pLCL_mu, TLCL_mu = 0, 0, p[0], T_K[0]

        cape_summary.append((name, run, CAPE, CIN, MUCAPE))

        # ── dry adiabats (background) ─────────────────────────────────────
        for th_C in range(-40, 100, 10):
            th_K = th_C + 273.15
            p_da = np.linspace(P_BOT, P_TOP, 300)
            T_da = th_K * (p_da / P0) ** kd - 273.15
            x_da = skewx(T_da, p_da)
            mask = (x_da >= T_MIN) & (x_da <= T_MAX)
            if mask.sum() > 1:
                ax.plot(x_da[mask], p_da[mask], color="#bbddbb", lw=0.6, zorder=1)

        # ── moist adiabats (background) ───────────────────────────────────
        for th_e_C in range(-20, 50, 5):
            T_start = th_e_C + 273.15
            p_ma, T_ma = moist_adiabat(T_start, P_BOT, p_top=P_TOP)
            T_ma_C = T_ma - 273.15
            x_ma = skewx(T_ma_C, p_ma)
            mask = (x_ma >= T_MIN) & (x_ma <= T_MAX)
            if mask.sum() > 1:
                ax.plot(x_ma[mask], p_ma[mask], color="#bbccee", lw=0.6,
                        ls="--", zorder=1)

        # ── mixing ratio lines (background) ──────────────────────────────
        for w_g in [1, 2, 4, 8, 12, 16, 20]:   # g/kg
            w = w_g / 1000.0
            p_mr = np.linspace(P_BOT, 400, 200)
            e_mr = w * p_mr / (eps + w)
            T_mr = 243.5 / (17.67 / np.log(e_mr / 6.112) - 1) + 273.15 - 273.15
            x_mr = skewx(T_mr, p_mr)
            mask = (x_mr >= T_MIN) & (x_mr <= T_MAX) & (p_mr <= P_BOT)
            if mask.sum() > 1:
                ax.plot(x_mr[mask], p_mr[mask], color="#99bb99", lw=0.5,
                        ls=":", zorder=1)
                ax.text(x_mr[mask][-1], p_mr[mask][-1], f"{w_g}",
                        fontsize=5, color="#559955", va="top")

        # ── temperature and dewpoint profiles ────────────────────────────
        x_T  = skewx(T_C,  p)
        x_Td = skewx(Td_C, p)
        ax.plot(x_T,  p, color="#d62728", lw=2.0, zorder=4, label="Temp")
        ax.plot(x_Td, p, color="#1f77b4", lw=2.0, zorder=4, label="Dewpoint")

        # ── parcel path ───────────────────────────────────────────────────
        th0 = theta(T_K[0], p[0])
        TL_K, pL_hPa = TLCL, pLCL

        # dry segment: surface → LCL
        p_dry = np.linspace(p[0], pL_hPa, 50)
        T_dry = th0 * (p_dry / P0) ** kd - 273.15
        ax.plot(skewx(T_dry, p_dry), p_dry, color="#ff7f0e", lw=1.5,
                ls="--", zorder=5)

        # moist segment: LCL → top
        p_wet, T_wet_K = moist_adiabat(TL_K, pL_hPa, p_top=P_TOP)
        T_wet_C = T_wet_K - 273.15
        ax.plot(skewx(T_wet_C, p_wet), p_wet, color="#ff7f0e", lw=1.5,
                ls="-", zorder=5, label="Parcel")

        # LCL marker
        ax.plot(skewx(TL_K - 273.15, pL_hPa), pL_hPa,
                "o", color="#ff7f0e", ms=5, zorder=6)

        # dotted line: surface dewpoint → LCL (saturation point)
        ax.plot([skewx(Td_C[0], p[0]), skewx(TL_K - 273.15, pL_hPa)],
                [p[0], pL_hPa], color="#ff7f0e", lw=1.0, ls=":", zorder=5)

        # ── most-unstable parcel path (purple) ──────────────────────────────
        th0_mu = theta(T_K[mu_idx], p[mu_idx])
        p_dry_mu = np.linspace(p[mu_idx], pLCL_mu, 50)
        T_dry_mu = th0_mu * (p_dry_mu / P0) ** kd - 273.15
        ax.plot(skewx(T_dry_mu, p_dry_mu), p_dry_mu, color="purple", lw=1.5,
                ls="--", zorder=5)
        p_wet_mu, T_wet_mu_K = moist_adiabat(TLCL_mu, pLCL_mu, p_top=P_TOP)
        ax.plot(skewx(T_wet_mu_K - 273.15, p_wet_mu), p_wet_mu, color="purple",
                lw=1.5, zorder=5, label="MU Parcel")
        ax.plot(skewx(TLCL_mu - 273.15, pLCL_mu), pLCL_mu,
                "o", color="purple", ms=5, zorder=6)

        # dotted line: surface dewpoint → MU LCL (saturation point)
        ax.plot([skewx(Td_C[0], p[0]), skewx(TLCL_mu - 273.15, pLCL_mu)],
                [p[0], pLCL_mu], color="purple", lw=1.0, ls=":", zorder=5)

        # ── wind barbs ────────────────────────────────────────────────────
        # subsample to ~every 50 hPa
        p_barb_targets = np.arange(1000, P_TOP - 1, -50)
        for pt in p_barb_targets:
            i = np.argmin(np.abs(p - pt))
            if abs(p[i] - pt) > 30:
                continue
            u_kt = u[i] * 1.94384
            v_kt = v[i] * 1.94384
            ax.barbs(T_MAX - 2, p[i], u_kt, v_kt,
                     length=5, linewidth=0.8, barbcolor="k",
                     flagcolor="k", zorder=6)

        # ── axes formatting ───────────────────────────────────────────────
        ax.set_yscale("log")
        ax.set_ylim(P_BOT, P_TOP)
        ax.yaxis.set_major_formatter(ticker.ScalarFormatter())
        ax.set_yticks(PRES_LEVELS)
        ax.set_yticklabels([str(lv) for lv in PRES_LEVELS], fontsize=7)

        ax.set_xlim(T_MIN, T_MAX)
        ax.set_xticks(range(T_MIN, T_MAX + 1, 10))
        ax.set_xticklabels([f"{t}°" for t in range(T_MIN, T_MAX + 1, 10)], fontsize=7)
        ax.set_xlabel("Temperature (°C, skewed)", fontsize=8)
        ax.set_ylabel("Pressure (hPa)", fontsize=8)
        ax.grid(True, which="both", ls="--", lw=0.3, alpha=0.4)

        # horizontal pressure lines
        for lv in PRES_LEVELS:
            ax.axhline(lv, color="#aaaaaa", lw=0.4, zorder=0)

        title_str  = build_title(gj, name, run)
        ax.set_title(title_str, fontsize=8, fontweight="bold", color="#333333", pad=3)

        # ── 700-500 mb temperature difference (static instability) ─────────
        try:
            p_dec = p[::-1]            # ascending pressure for interp
            T_dec = T_C[::-1]
            T700 = float(np.interp(700, p_dec, T_dec))
            T500 = float(np.interp(500, p_dec, T_dec))
            dT_7_5 = T700 - T500
            if dT_7_5 > 18:
                cb_tag = "CB"
                band_alpha = 0.45
            elif dT_7_5 >= 16:
                cb_tag = "TCU"
                band_alpha = 0.18
            else:
                cb_tag = ""
                band_alpha = 0.0
            if band_alpha > 0:
                ax.axhspan(500, 700, color="#ff7f00", alpha=band_alpha, zorder=2)
                ax.text(T_MAX - 2, np.sqrt(500*700), cb_tag, transform=ax.transData,
                         fontsize=22, fontweight="bold", color="#ff7f00",
                         alpha=0.9, ha="right", va="center", zorder=3)
            label_7_5 = f"700-500mb ΔT {dT_7_5:.1f}°C" + (f"  [{cb_tag}]" if cb_tag else "")
            ax.text(0.02, 0.02, label_7_5, transform=ax.transAxes,
                     fontsize=7, fontweight="bold", color="#ff7f00",
                     ha="left", va="bottom", zorder=10)
        except Exception:
            pass

    for i in range(n, ROWS * COLS):
        axes[i // COLS][i % COLS].set_visible(False)

    run_date = (t12 if PLOT_RUN == "12Z" else t00).strftime("%Y-%m-%d")
    fig.suptitle(f"Skew-T Log-P  —  {PLOT_RUN}  ({run_date})",
                 fontsize=14, fontweight="bold", y=1.005)
    plt.tight_layout()
    plt.close(fig)

    # ── save individual PNGs and bundle into zip ──────────────────────────
    import io, zipfile, base64

    zip_buf = io.BytesIO()
    saved_files = []
    profile_png_b64 = {}     # {(name, run): base64 PNG string} — used by the coverage map cell
    station_instability = {} # {(name, run): {"tag": "CB"/"TCU"/"", "dT": float}} — used by the coverage map cell
    station_cape = {}        # {(name, run): {"CAPE": float, "MUCAPE": float}} — used by the coverage map cell

    with zipfile.ZipFile(zip_buf, "w", zipfile.ZIP_DEFLATED) as zf:
        # combined overview PNG (mirrors the wind-speed overview)
        tephi_overview_name = f"soundings_{PLOT_RUN}_{run_date}.png"
        ov_buf = io.BytesIO()
        fig.savefig(ov_buf, dpi=150, bbox_inches="tight", format="png")
        ov_buf.seek(0)
        tephi_overview_bytes = ov_buf.read()
        zf.writestr(tephi_overview_name, tephi_overview_bytes)
        saved_files.append(tephi_overview_name)
        tephi_overview_b64 = base64.b64encode(tephi_overview_bytes).decode()

        for idx, (name, run) in enumerate(station_keys):
            gj = raw_geojson[name][run]
            p, T_K, Td_K, u, v, h = parse_full(gj)
            if len(p) < 5:
                continue

            si   = np.argsort(p)[::-1]
            p    = p[si];  T_K = T_K[si];  Td_K = Td_K[si]
            u    = u[si];  v   = v[si]
            T_C  = T_K - 273.15
            Td_C = Td_K - 273.15

            try:
                CAPE, CIN, pLCL, TLCL = compute_cape_cin(p, T_K, Td_K)
            except Exception:
                CAPE, CIN, pLCL, TLCL = 0, 0, p[0], T_K[0]

            try:
                mu_idx_s = find_mu_index(p, T_K)
                MUCAPE, MUCIN, pLCL_mu, TLCL_mu = compute_cape_from_level(p, T_K, Td_K, mu_idx_s, Td_surface=Td_K[0])
            except Exception:
                mu_idx_s = 0
                MUCAPE, MUCIN, pLCL_mu, TLCL_mu = 0, 0, p[0], T_K[0]

            station_cape[(name, run)] = {"CAPE": CAPE, "MUCAPE": MUCAPE}

            fig_s, ax_s = plt.subplots(figsize=(7, 9))

            # background: dry adiabats
            for th_C in range(-40, 100, 10):
                th_K = th_C + 273.15
                p_da = np.linspace(P_BOT, P_TOP, 300)
                T_da = th_K * (p_da / P0) ** kd - 273.15
                x_da = skewx(T_da, p_da)
                mask = (x_da >= T_MIN) & (x_da <= T_MAX)
                if mask.sum() > 1:
                    ax_s.plot(x_da[mask], p_da[mask], color="#bbddbb", lw=0.6, zorder=1)

            # background: moist adiabats
            for th_e_C in range(-20, 50, 5):
                T_start = th_e_C + 273.15
                p_ma, T_ma = moist_adiabat(T_start, P_BOT, p_top=P_TOP)
                T_ma_C = T_ma - 273.15
                x_ma = skewx(T_ma_C, p_ma)
                mask = (x_ma >= T_MIN) & (x_ma <= T_MAX)
                if mask.sum() > 1:
                    ax_s.plot(x_ma[mask], p_ma[mask], color="#bbccee", lw=0.6, ls="--", zorder=1)

            # background: mixing ratio lines
            for w_g in [1, 2, 4, 8, 12, 16, 20]:
                w = w_g / 1000.0
                p_mr = np.linspace(P_BOT, 400, 200)
                e_mr = w * p_mr / (eps + w)
                T_mr = 243.5 / (17.67 / np.log(e_mr / 6.112) - 1)
                x_mr = skewx(T_mr, p_mr)
                mask = (x_mr >= T_MIN) & (x_mr <= T_MAX)
                if mask.sum() > 1:
                    ax_s.plot(x_mr[mask], p_mr[mask], color="#99bb99", lw=0.5, ls=":", zorder=1)
                    ax_s.text(x_mr[mask][-1], p_mr[mask][-1], f"{w_g}",
                              fontsize=5, color="#559955", va="top")

            # profiles
            ax_s.plot(skewx(T_C,  p), p, color="#d62728", lw=2.0, zorder=4, label="Temp")
            ax_s.plot(skewx(Td_C, p), p, color="#1f77b4", lw=2.0, zorder=4, label="Dewpoint")

            # parcel path
            th0 = theta(T_K[0], p[0])
            p_dry = np.linspace(p[0], pLCL, 50)
            T_dry = th0 * (p_dry / P0) ** kd - 273.15
            ax_s.plot(skewx(T_dry, p_dry), p_dry, color="#ff7f0e", lw=1.5, ls="--", zorder=5)
            p_wet, T_wet_K = moist_adiabat(TLCL, pLCL, p_top=P_TOP)
            ax_s.plot(skewx(T_wet_K - 273.15, p_wet), p_wet,
                      color="#ff7f0e", lw=1.5, zorder=5, label="Parcel")
            ax_s.plot(skewx(TLCL - 273.15, pLCL), pLCL,
                      "o", color="#ff7f0e", ms=5, zorder=6)

            # dotted line: surface dewpoint → LCL (saturation point)
            ax_s.plot([skewx(Td_C[0], p[0]), skewx(TLCL - 273.15, pLCL)],
                      [p[0], pLCL], color="#ff7f0e", lw=1.0, ls=":", zorder=5)

            # most-unstable parcel path (purple)
            th0_mu_s = theta(T_K[mu_idx_s], p[mu_idx_s])
            p_dry_mu_s = np.linspace(p[mu_idx_s], pLCL_mu, 50)
            T_dry_mu_s = th0_mu_s * (p_dry_mu_s / P0) ** kd - 273.15
            ax_s.plot(skewx(T_dry_mu_s, p_dry_mu_s), p_dry_mu_s, color="purple",
                      lw=1.5, ls="--", zorder=5)
            p_wet_mu_s, T_wet_mu_s_K = moist_adiabat(TLCL_mu, pLCL_mu, p_top=P_TOP)
            ax_s.plot(skewx(T_wet_mu_s_K - 273.15, p_wet_mu_s), p_wet_mu_s,
                      color="purple", lw=1.5, zorder=5, label="MU Parcel")
            ax_s.plot(skewx(TLCL_mu - 273.15, pLCL_mu), pLCL_mu,
                      "o", color="purple", ms=5, zorder=6)

            # dotted line: surface dewpoint → MU LCL (saturation point)
            ax_s.plot([skewx(Td_C[0], p[0]), skewx(TLCL_mu - 273.15, pLCL_mu)],
                      [p[0], pLCL_mu], color="purple", lw=1.0, ls=":", zorder=5)

            # wind barbs
            for pt in np.arange(1000, P_TOP - 1, -50):
                i = np.argmin(np.abs(p - pt))
                if abs(p[i] - pt) > 30:
                    continue
                ax_s.barbs(T_MAX - 2, p[i], u[i]*1.94384, v[i]*1.94384,
                           length=5, linewidth=0.8, barbcolor="k", flagcolor="k", zorder=6)

            ax_s.set_yscale("log")
            ax_s.set_ylim(P_BOT, P_TOP)
            ax_s.yaxis.set_major_formatter(ticker.ScalarFormatter())
            ax_s.set_yticks(PRES_LEVELS)
            ax_s.set_yticklabels([str(lv) for lv in PRES_LEVELS], fontsize=8)
            ax_s.set_xlim(T_MIN, T_MAX)
            ax_s.set_xticks(range(T_MIN, T_MAX + 1, 10))
            ax_s.set_xticklabels([f"{t}°" for t in range(T_MIN, T_MAX + 1, 10)], fontsize=8)
            for lv in PRES_LEVELS:
                ax_s.axhline(lv, color="#aaaaaa", lw=0.4, zorder=0)
            ax_s.grid(True, which="both", ls="--", lw=0.3, alpha=0.4)
            ax_s.set_xlabel("Temperature (°C, skewed)", fontsize=9)
            ax_s.set_ylabel("Pressure (hPa)", fontsize=9)
            ax_s.legend(fontsize=7, loc="upper left")

            ax_s.set_title(build_title(gj, name, run),
                           fontsize=10, fontweight="bold", color="#333333")

            # ── 700-500 mb temperature difference (static instability) ─────
            try:
                p_dec = p[::-1]
                T_dec = T_C[::-1]
                T700 = float(np.interp(700, p_dec, T_dec))
                T500 = float(np.interp(500, p_dec, T_dec))
                dT_7_5 = T700 - T500
                if dT_7_5 > 18:
                    cb_tag = "CB"
                    band_alpha = 0.45
                elif dT_7_5 >= 16:
                    cb_tag = "TCU"
                    band_alpha = 0.18
                else:
                    cb_tag = ""
                    band_alpha = 0.0
                if band_alpha > 0:
                    ax_s.axhspan(500, 700, color="#ff7f00", alpha=band_alpha, zorder=2)
                    ax_s.text(T_MAX - 2, np.sqrt(500*700), cb_tag, transform=ax_s.transData,
                               fontsize=28, fontweight="bold", color="#ff7f00",
                               alpha=0.9, ha="right", va="center", zorder=3)
                label_7_5 = f"700-500mb ΔT {dT_7_5:.1f}°C" + (f"  [{cb_tag}]" if cb_tag else "")
                ax_s.text(0.02, 0.02, label_7_5, transform=ax_s.transAxes,
                           fontsize=8, fontweight="bold", color="#ff7f00",
                           ha="left", va="bottom", zorder=10)
                station_instability[(name, run)] = {"tag": cb_tag, "dT": dT_7_5}
            except Exception:
                station_instability[(name, run)] = {"tag": "", "dT": None}

            fig_s.tight_layout()

            # filename: StationName_12Z01JUN2026_PROFILE.png
            run_dt  = t12 if run == "12Z" else t00
            run_tag = run_dt.strftime(f"%H%Z%d%b%Y").upper().replace("UTC", "Z")
            safe    = name.replace(" ", "_")
            fname   = f"{safe}_{run_tag}_PROFILE.png"

            buf_s = io.BytesIO()
            fig_s.savefig(buf_s, dpi=150, bbox_inches="tight", format="png")
            buf_s.seek(0)
            png_bytes = buf_s.read()
            zf.writestr(fname, png_bytes)
            saved_files.append(fname)
            profile_png_b64[(name, run)] = base64.b64encode(png_bytes).decode()
            plt.close(fig_s)

    # ── save zip to disk (tephi_zip_b64 is reused later for the map legend) ──
    zip_buf.seek(0)
    tephi_zip_b64 = base64.b64encode(zip_buf.read()).decode()
    tephi_zip_filename = f"soundings_{PLOT_RUN}_{run_date}.zip"
    tephi_zip_path = os.path.join(OUTPUT_DIR, tephi_zip_filename)

    with open(tephi_zip_path, "wb") as f:
        zip_buf.seek(0)
        f.write(zip_buf.read())

    print(f"Saved: {tephi_zip_path}  ({len(saved_files)} station PNGs)")


    # CAPE summary table removed — CAPE/MUCAPE values not yet validated.

# @title Station Coverage Map (00Z / 12Z)
import folium
import json as _json

GREEN = "#2ca02c"
GREY  = "#bbbbbb"

def _norm(s):
    return s.lower().replace(",", "").strip()

def _match_raw_geojson_key(sta_name):
    """Find the raw_geojson top-level key that best matches a UPPER_AIR_STATIONS name."""
    target = _norm(sta_name)
    # exact match first
    for k in raw_geojson.keys():
        if _norm(k) == target:
            return k
    # fallback: substring match either direction
    for k in raw_geojson.keys():
        kn = _norm(k)
        if kn in target or target in kn:
            return k
    return None

def _half_circle_svg(map_key, has00, has12, tag00="", tag12="", pw00=None, pw12=None,
                      cape00=False, cape12=False, mucape00=False, mucape12=False):
    c00 = GREEN if has00 else GREY
    c12 = GREEN if has12 else GREY
    key00 = f"{map_key}|00Z"
    key12 = f"{map_key}|12Z"

    def _tag_color(tag):
        if tag == "CB":
            return "#d62728"
        if tag == "TCU":
            return "#ff7f0e"
        return None

    # two small badges side by side (00Z left, 12Z right), shown only if present
    def _single_badge(tag):
        color = _tag_color(tag)
        if not color:
            return """<div style="font-size:8px;font-weight:bold;color:transparent;
                padding:0px 3px;">--</div>"""
        return f"""<div style="font-size:8px;font-weight:bold;color:white;
            background:{color};border-radius:3px;padding:0px 3px;
            text-align:center;white-space:nowrap;">{tag}</div>"""

    badge_html = ""
    if tag00 or tag12:
        badge_html = f"""<div style="display:flex;flex-direction:row;gap:1px;margin-bottom:1px;">
            {_single_badge(tag00)}{_single_badge(tag12)}
            </div>"""

    # CAPE / MUCAPE badges — split 00Z (left pair) / 12Z (right pair), shown only when positive
    def _cape_badge(positive, label, color):
        if not positive:
            return ""
        return f"""<div style="font-size:7px;font-weight:bold;color:white;
            background:{color};border-radius:2px;padding:0px 2px;
            text-align:center;white-space:nowrap;">{label}</div>"""

    cape_row_html = ""
    if cape00 or cape12 or mucape00 or mucape12:
        left  = _cape_badge(cape00, "C", "#2ca02c") + _cape_badge(mucape00, "MU", "#9467bd")
        right = _cape_badge(cape12, "C", "#2ca02c") + _cape_badge(mucape12, "MU", "#9467bd")
        cape_row_html = f"""<div style="display:flex;flex-direction:row;gap:4px;margin-bottom:1px;">
            <div style="display:flex;gap:1px;">{left}</div>
            <div style="display:flex;gap:1px;">{right}</div>
            </div>"""

    # wind label line, e.g. "35/42kt" (00Z/12Z), shown below the circle
    def _fmt(pw):
        return f"{pw:.0f}" if pw is not None else "-"
    wind_label_html = ""
    if pw00 is not None or pw12 is not None:
        wind_label_html = f"""<div style="font-size:8px;font-weight:bold;color:#222;
            background:rgba(255,255,255,0.85);border-radius:3px;padding:0px 2px;
            text-align:center;white-space:nowrap;margin-top:1px;">{_fmt(pw00)}/{_fmt(pw12)}kt</div>"""

    return f"""
    <div style="display:flex;flex-direction:column;align-items:center;">
      {cape_row_html}
      {badge_html}
      <svg width="20" height="20" viewBox="0 0 22 22" xmlns="http://www.w3.org/2000/svg">
        <path d="M11,11 L11,1 A10,10 0 0,0 11,21 Z" fill="{c00}" stroke="#333" stroke-width="0.7"
              style="cursor:pointer" onclick="openSoundingBoth('{map_key}')"/>
        <path d="M11,11 L11,21 A10,10 0 0,0 11,1 Z" fill="{c12}" stroke="#333" stroke-width="0.7"
              style="cursor:pointer" onclick="openSoundingBoth('{map_key}')"/>
      </svg>
      {wind_label_html}
    </div>
    """

# build map
lats = [s["lat"] for s in UPPER_AIR_STATIONS]
lons = [s["lon"] for s in UPPER_AIR_STATIONS]
m = folium.Map(location=[sum(lats)/len(lats), sum(lons)/len(lons)],
                zoom_start=3, tiles="CartoDB positron")

# embed both PROFILE and WINDS PNGs as a JS lookup, keyed "Name|Run|Type"
png_lookup = {}
for (sta, run), b64 in profile_png_b64.items():
    png_lookup[f"{sta}|{run}|PROFILE"] = b64
for (sta, run), b64 in wind_png_b64.items():
    png_lookup[f"{sta}|{run}|WINDS"] = b64

png_script = folium.Element(f"""
<script>

var pngData = {_json.dumps(png_lookup)};
var overviewData = {{
    "tephi": {_json.dumps(tephi_overview_b64) if 'tephi_overview_b64' in dir() else 'null'},
    "wind": {_json.dumps(wind_overview_b64) if 'wind_overview_b64' in dir() else 'null'}
}};
function openOverview(kind) {{
    var b64 = overviewData[kind];
    if (!b64) {{
        alert("Overview image not available");
        return;
    }}
    var w = window.open("");
    w.document.write('<title>' + kind + ' overview</title><img src="data:image/png;base64,' + b64 + '" style="max-width:100%;">');
}}
function openSounding(baseKey) {{
    var profileKey = baseKey + "|PROFILE";
    var windsKey = baseKey + "|WINDS";
    var html = '<title>' + baseKey + '</title>';
    var found = false;
    if (pngData[profileKey]) {{
        html += '<h3 style="font-family:sans-serif;">Tephigram / CAPE</h3>' +
                '<img src="data:image/png;base64,' + pngData[profileKey] + '" style="max-width:100%;">';
        found = true;
    }}
    if (pngData[windsKey]) {{
        html += '<h3 style="font-family:sans-serif;">Wind Speed Profile</h3>' +
                '<img src="data:image/png;base64,' + pngData[windsKey] + '" style="max-width:100%;">';
        found = true;
    }}
    if (found) {{
        var w = window.open("");
        w.document.write(html);
    }} else {{
        alert("No sounding available for " + baseKey);
    }}
}}

function _runColumnHtml(stationKey, runLabel) {{
    var profileKey = stationKey + "|" + runLabel + "|PROFILE";
    var windsKey = stationKey + "|" + runLabel + "|WINDS";
    var hasAny = false;
    var inner = '<h3 style="font-family:sans-serif;margin:4px 0;">' + runLabel + '</h3>';
    if (pngData[profileKey]) {{
        inner += '<div style="font-family:sans-serif;font-size:12px;font-weight:bold;margin-top:6px;">Tephigram / CAPE</div>' +
                 '<img src="data:image/png;base64,' + pngData[profileKey] + '" style="max-width:100%;">';
        hasAny = true;
    }}
    if (pngData[windsKey]) {{
        inner += '<div style="font-family:sans-serif;font-size:12px;font-weight:bold;margin-top:6px;">Wind Speed Profile</div>' +
                 '<img src="data:image/png;base64,' + pngData[windsKey] + '" style="max-width:100%;">';
        hasAny = true;
    }}
    if (!hasAny) {{
        inner += '<div style="font-family:sans-serif;font-size:13px;color:#888;padding:20px 0;">Not available</div>';
    }}
    return inner;
}}

function openSoundingBoth(stationKey) {{
    var html = '<title>' + stationKey + '</title>' +
        '<div style="display:flex;flex-direction:row;width:100%;">' +
        '<div style="flex:1;padding:8px;box-sizing:border-box;">' + _runColumnHtml(stationKey, "00Z") + '</div>' +
        '<div style="width:1px;background:#ccc;"></div>' +
        '<div style="flex:1;padding:8px;box-sizing:border-box;">' + _runColumnHtml(stationKey, "12Z") + '</div>' +
        '</div>';
    var w = window.open("");
    w.document.write(html);
}}
</script>
""")
m.get_root().html.add_child(png_script)

def _run_summary(name, map_key, run_label):
    """Build a short summary string for one run: peak wind <800mb + CB/TCU tag."""
    parts = []
    pw_dict = globals().get('station_peak_wind', {})
    pw = pw_dict.get((name, run_label))
    if pw is None:
        pw = pw_dict.get((map_key, run_label))
    if pw is not None:
        parts.append(f"{pw:.0f}kt<800mb")
    inst_dict = globals().get('station_instability', {})
    inst = inst_dict.get((name, run_label))
    if not inst:
        inst = inst_dict.get((map_key, run_label))
    if inst and inst.get("tag"):
        parts.append(inst["tag"])
    return " ".join(parts)

for s in UPPER_AIR_STATIONS:
    name = s["name"]
    matched_key = _match_raw_geojson_key(name)
    if matched_key:
        has00 = bool(raw_geojson.get(matched_key, {}).get("00Z"))
        has12 = bool(raw_geojson.get(matched_key, {}).get("12Z"))
    else:
        has00 = has12 = False
    # use the matched raw_geojson key as the map/PNG lookup key, since that's
    # what the profile/wind export loops used to build their dictionaries
    map_key = matched_key if matched_key else name

    sum00 = _run_summary(name, map_key, "00Z") if has00 else ""
    sum12 = _run_summary(name, map_key, "12Z") if has12 else ""
    _inst_dict = globals().get('station_instability', {})
    tag00 = (_inst_dict.get((name, "00Z")) or _inst_dict.get((map_key, "00Z"), {})).get("tag", "") if has00 else ""
    tag12 = (_inst_dict.get((name, "12Z")) or _inst_dict.get((map_key, "12Z"), {})).get("tag", "") if has12 else ""

    _pw_dict = globals().get('station_peak_wind', {})
    pw00 = (_pw_dict.get((name, "00Z")) if _pw_dict.get((name, "00Z")) is not None
            else _pw_dict.get((map_key, "00Z"))) if has00 else None
    pw12 = (_pw_dict.get((name, "12Z")) if _pw_dict.get((name, "12Z")) is not None
            else _pw_dict.get((map_key, "12Z"))) if has12 else None

    _cape_dict = globals().get('station_cape', {})
    _cape00 = (_cape_dict.get((name, "00Z")) or _cape_dict.get((map_key, "00Z"))) if has00 else None
    _cape12 = (_cape_dict.get((name, "12Z")) or _cape_dict.get((map_key, "12Z"))) if has12 else None
    cape00   = bool(_cape00 and (_cape00.get("CAPE") or 0) > 0)
    cape12   = bool(_cape12 and (_cape12.get("CAPE") or 0) > 0)
    mucape00 = bool(_cape00 and (_cape00.get("MUCAPE") or 0) > 0)
    mucape12 = bool(_cape12 and (_cape12.get("MUCAPE") or 0) > 0)

    icon_html = _half_circle_svg(map_key, has00, has12, tag00=tag00, tag12=tag12, pw00=pw00, pw12=pw12,
                                  cape00=cape00, cape12=cape12, mucape00=mucape00, mucape12=mucape12)

    tooltip_lines = [name]
    tooltip_lines.append(f"00Z: {'✓ ' + sum00 if has00 else '✗'}")
    tooltip_lines.append(f"12Z: {'✓ ' + sum12 if has12 else '✗'}")
    if cape00 or mucape00 or cape12 or mucape12:
        def _cape_tag(c, mu):
            parts = []
            if c:  parts.append("CAPE+")
            if mu: parts.append("MUCAPE+")
            return "/".join(parts) if parts else "-"
        tooltip_lines.append(f"00Z: {_cape_tag(cape00, mucape00)} &nbsp;&nbsp; 12Z: {_cape_tag(cape12, mucape12)}")
    tooltip_text = "<br>".join(tooltip_lines)

    has_wind_label = (pw00 is not None) or (pw12 is not None)
    has_cape_row = cape00 or cape12 or mucape00 or mucape12
    icon_h = 22 + (10 if (tag00 or tag12) else 0) + (10 if has_wind_label else 0) + (10 if has_cape_row else 0)
    icon_size = (32, icon_h)
    icon_anchor = (16, icon_h - 11)

    folium.Marker(
        location=[s["lat"], s["lon"]],
        icon=folium.DivIcon(html=icon_html, icon_size=icon_size, icon_anchor=icon_anchor),
        tooltip=folium.Tooltip(tooltip_text, sticky=True)
    ).add_to(m)

# legend + zip download buttons
tephi_btn = ""
if 'tephi_zip_b64' in dir() and 'tephi_zip_filename' in dir():
    tephi_btn = f"""
      <a download="{tephi_zip_filename}"
         href="data:application/zip;base64,{tephi_zip_b64}"
         style="display:inline-block;padding:6px 12px;background:#ff7f0e;
                color:white;font-weight:bold;border-radius:5px;
                text-decoration:none;font-size:11px;margin-top:6px;">
        ⬇ Tephigram ZIP
      </a>
    """

wind_btn = ""
if 'wind_zip_b64' in dir() and 'wind_zip_filename' in dir():
    wind_btn = f"""
      <a download="{wind_zip_filename}"
         href="data:application/zip;base64,{wind_zip_b64}"
         style="display:inline-block;padding:6px 12px;background:#1a6fb5;
                color:white;font-weight:bold;border-radius:5px;
                text-decoration:none;font-size:11px;margin-top:6px;margin-left:6px;">
        ⬇ Wind ZIP
      </a>
    """


tephi_overview_btn = ""
if 'tephi_overview_b64' in dir():
    tephi_overview_btn = """
      <a href="#" onclick="openOverview('tephi');return false;"
         style="display:inline-block;padding:6px 12px;background:#fff;
                color:#ff7f0e;font-weight:bold;border:1.5px solid #ff7f0e;border-radius:5px;
                text-decoration:none;font-size:11px;margin-top:6px;margin-left:6px;">
        ⬚ All Tephigrams
      </a>
    """


wind_overview_btn = ""
if 'wind_overview_b64' in dir():
    wind_overview_btn = """
      <a href="#" onclick="openOverview('wind');return false;"
         style="display:inline-block;padding:6px 12px;background:#fff;
                color:#1a6fb5;font-weight:bold;border:1.5px solid #1a6fb5;border-radius:5px;
                text-decoration:none;font-size:11px;margin-top:6px;margin-left:6px;">
        ⬚ All Winds
      </a>
    """

legend_html = f"""
<div style="position: fixed; bottom: 20px; left: 20px; z-index:9999;
            background:white; padding:10px 14px; border-radius:6px;
            box-shadow:0 1px 4px rgba(0,0,0,0.3); font-size:12px; font-family:sans-serif;">
  <b>Sounding availability</b><br>
  Left half = 00Z &nbsp;&nbsp; Right half = 12Z<br>
  <span style="background:#2ca02c;color:white;border-radius:2px;padding:0px 3px;font-size:9px;">C</span> CAPE&gt;0 &nbsp;
  <span style="background:#9467bd;color:white;border-radius:2px;padding:0px 3px;font-size:9px;">MU</span> MUCAPE&gt;0
  (left badge pair = 00Z, right = 12Z)<br>
  <span style="color:#2ca02c;">●</span> Available &nbsp;&nbsp;
  <span style="color:#bbbbbb;">●</span> Missing<br>
  <i>Click a half-circle to open that run's PNG</i><br>
  {tephi_btn}{wind_btn}<br>
  {tephi_overview_btn}{wind_overview_btn}
</div>
"""
m.get_root().html.add_child(folium.Element(legend_html))

run_date_map = (t12 if PLOT_RUN == "12Z" else t00).strftime("%Y-%m-%d")
map_filename = f"index.html"
map_path = os.path.join(OUTPUT_DIR, map_filename)
m.save(map_path)
print(f"Saved: {map_path}")
